In [1]:
import nbformat.v2.nbjson
import  numpy as np
import sys

## The Basics
is for creating multidimensional libraries
- python lists are slow
- numpy is much faster
### Why is numpy faster?
- Numpy is Fixed Type
    - type in numpy can be specified e.i. 5 is defaulted to Int32 but Can go as low as Int8
    - but in list this would be x7 larger
- Numpy utilises Contiguous Memory
    - List in python can be scattered through memory blocks. The list itself contains pointers to the actual elements
    - In Numpy all elements are in neighbouring memory blocks. Something about SIMD
- Numpy arrays have all features that list have AND more. For example, you can multiply matrices

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [5]:
b = np.array([[9.,8.,7.],[6.,5.,4.]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


### How to get Dimensions

In [10]:
print(f'a dimensions is {a.ndim}')
print(f'b dimensions is {b.ndim}')

a dimensions is 1
b dimensions is 2


### How to get shape? (it's a vector???) #need more researche

In [11]:
print(f'a shape is {a.shape}')
print(f'b shape is {b.shape}')

a shape is (3,)
b shape is (2, 3)


### Type

In [15]:
print(f'a data type is {a.dtype}')
c = np.array([1,2,3],dtype='int8')
print(f'c data type is {c.dtype}')


a data type is int64
c data type is int8


### Get size per item and total

In [22]:
a.itemsize

1

In [25]:
c.nbytes

3

In [24]:
c.nbytes

3

## Accessing/Changing specific elements

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


### How to get a specific element [r, c]

In [28]:
# Let's say we want to get 13 from a
print(a[1,5])

13


In [29]:
# Get a specific row
print(a[1, :])

[ 8  9 10 11 12 13 14]


In [31]:
# And get a specific column
print(a[:, 2])

[ 3 10]


In [35]:
# Getting a little more fancy
# [startindex:endindex:stepsize]
print(a[0,1:-1:2]) # huh??

[2 4 6]


#### All of this works for assignment too

### 3D example:

In [36]:
three_d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(three_d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Get specific element
(work outside in)

In [38]:
print(three_d[0, 1, 1])

4


In [39]:
print(three_d[:, 1, :])

[[3 4]
 [7 8]]


In [48]:
# Let's try replacing
three_d_new = three_d.copy() # doing this just so I don't change original
print(f'Old array:\n{three_d_new}')
three_d_new[:,1,:] = [[9, 9],[8,8]]
print(f'\nAfter change:\n{three_d_new}')


Old array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
After change:
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]
