In [1]:
import numpy as np

# Implementing Conway's Game of Life in python using numpy

In [2]:
a = np.arange(25).reshape((5,5))
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

300
[50 55 60 65 70]
[ 10  35  60  85 110]


In [3]:
print(a[a % 2 ==0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24]


In [4]:
arr_b = np.array([[ 0,  1,  2],
   [ 3,  4,  5],
   [ 6,  7,  8],
   [ 9, 10, 11]])
arr_c = np.array([[ 0,  1,  2,  3],
   [ 4,  5,  6,  7],
   [ 8,  9, 10, 11]])

print(np.dot(arr_b, arr_c))

[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


### Exercise: Sum of all elements in a 2D array

In [5]:
big_array = np.random.random(size=(10000, 10000))
print(big_array.sum())

50002127.23137431


### Exercise: Thinking in array indices¶


In [6]:
def roll_array(arr):
        return a[a-3]

# If your example replicates this output, it is good to go
a = np.array([2, 3, 4, 1])
roll_array(a)
# Should get output: `array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
import numpy as np

def odd_even(arr):
        return arr + (1, -1, 1, -1, 1, -1)

# If your example replicates this output, it is good to go
b = 5 * np.ones(shape=(6, )) # Initialize an array with all 5's
c = odd_even(b) # Should get output: `array([6, 4, 6, 4, 6, 4])
d = odd_even(c) # Should get output: `array([7, 3, 7, 3, 7, 3])
c

array([6., 4., 6., 4., 6., 4.])

In [76]:
map = np.random.randint(low=0, high=2, size=(6,6))
(
    map[0],
    map[-1],
    map[:, 0],
    map[:, -1],
) = (
    0,
    0,
    0,
    0,
)
# map = np.array([[0,0,0,0,0,0],[0,0,0,0,0,0],[0,1,1,1,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],[0,0,0,0,0,0],])

print(map)
map_after = np.zeros((6,6))
for i in range(1, 5):
    for j in range(1, 5):
        sum_of_all = np.sum(map[i-1:i+2,j-1:j+2]) - map[i,j]
        # Rules of life
        # print(f'{"#"*20}')
        # print(f'visited {i},{j} and sum is {sum_of_all}')
        # print(f'selection: \n{map[i-1:i+2,j-1:j+2]}')
        if sum_of_all <= 1:
            # print('sum_of_all <= 1')
            map_after[i,j] = 0
            continue
        if sum_of_all >= 4:
#             print('sum_of_all >= 4')
            map_after[i,j] = 0
            continue
        if map[i,j] == 1 and sum_of_all in range(2,4):
#             print('map[i,j] == 1 and sum_of_all in range(2,4)')
            map_after[i,j] = 1
            continue
        if map[i,j] == 0 and sum_of_all == 3:
#             print('map[i,j] == 0 and sum_of_all == 3')
            map_after[i,j] = 1
            continue
#         print('Out of cases')
        map_after[i,j] = 0
map_after


[[0 0 0 0 0 0]
 [0 0 1 1 1 0]
 [0 0 1 0 1 0]
 [0 1 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 0]]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [73]:
a = np.arange(25).reshape((5,5))
i,j = 1,1
# a[i,j]
print(np.sum(a[0:3,0:3]) - a[i,j])
print() #need to add two cuz selection is in second element is exclusive


48

