In [1]:
import numpy as np

## Numpy where() function
https://numpy.org/doc/2.3/reference/generated/numpy.where.html#numpy.where

In [7]:
a = np.random.randint(low=0, high=2, size=(10,10))
b = np.full(shape=(10,10), fill_value=32767, dtype='int16')
c = np.where(a == 0, a, b)
print(a)
print('\n')
print(b)
print('\n')
print(c)

[[0 0 1 0 1 0 1 0 0 1]
 [1 0 0 0 0 0 1 1 0 1]
 [0 0 0 1 0 0 1 1 0 1]
 [1 0 0 0 1 1 0 1 0 0]
 [0 1 0 1 1 1 0 1 0 0]
 [1 1 0 1 1 1 0 0 1 1]
 [1 1 1 0 0 1 1 0 1 1]
 [1 1 1 1 0 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1 1]
 [1 1 0 1 0 1 1 0 1 1]]


[[32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]
 [32767 32767 32767 32767 32767 32767 32767 32767 32767 32767]]


[[    0     0 32767     0 32767     0 32767     0     0 32767]
 [32767     0     0     0     0     0 32767 32767     0 32767]
 [    0 