In [1]:
import numpy as np
from numpy.ma.core import shape

## Misc

In [6]:
file_data = np.genfromtxt(
    'data.csv',
    delimiter=',',
    dtype='int32',
) # to load array from a file
print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Advanced Indexing

In [7]:
file_data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

You can index with a list in Numpy

In [8]:
file_data[file_data > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [15]:
a = np.array([1,2,3,4,5,6,7,8,9,])
a[[1,2,8]]

array([1, 4, 5, 8, 9])

In [17]:
a[[True,False,False,True,True,False,False,True,True]]
# This is kinda funny, but it ONLY works when boolean list is the same length as main array

array([1, 4, 5, 8, 9])

In [18]:
np.any(file_data > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [19]:
np.all(file_data > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [20]:
np.all(file_data > 50, axis=1)

array([False, False, False])

In [114]:
hw_matrix = np.arange(1, 31).reshape((6,5))
print(hw_matrix[2:4, 0:2],end='\n\n')

print(hw_matrix[[0,1,2,3],[1,2,3,4]],end='\n\n')

print(hw_matrix[[0,4,5],3:],end='\n\n')

[[11 12]
 [16 17]]

[ 2  8 14 20]

[[ 4  5]
 [24 25]
 [29 30]]

