In [1]:
import numpy as np

## Initializing Different Types of Arrays

In [8]:
# All 0s matrix
print(np.zeros((2,2)))
print(np.zeros((2,2,2),dtype='int8'))

[[0. 0.]
 [0. 0.]]
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [9]:
# All 1s matrix
print(np.ones((2,2)))

[[1. 1.]
 [1. 1.]]


In [10]:
# Any other number
np.full((2,2), 99, dtype='float16')

array([[99., 99.],
       [99., 99.]], dtype=float16)

In [11]:
# Any other number with full_like (not that usefull?)
a = np.array([[9.,8.,7.],[6.,5.,4.]])
np.full_like(a, 4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [20]:
# Random decimal numbers
print(np.random.rand(4,2))
print('####')
print(np.random.random_sample(a.shape))


[[0.68840631 0.4021406 ]
 [0.54351508 0.84478969]
 [0.26850625 0.20206221]
 [0.68785955 0.09359864]]
####
[[0.06969849 0.19286821 0.37630861]
 [0.84054641 0.73847953 0.27246402]]


In [23]:
# Random Int values
np.random.randint(-8,8, size=(3,3))

array([[-1,  7, -4],
       [ 2, -5, -5],
       [-4, -1,  5]], dtype=int32)

In [26]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


## Homework: create array like this:
```
[[1,1,1,1,1]
 [1,0,0,0,1]
 [1,0,9,0,1]
 [1,0,0,0,1]
 [1,1,1,1,1]]

In [41]:
hw = np.ones((5,5),dtype='int8')
hw[1:4,1:4] = 0
hw[2,2] = 9
hw

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

### Homework solution:

In [42]:
output = np.ones((5,5))
z = np.zeros((3,3))
z[1,1] = 9
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


I think that my solution is much better

---

Be careful when copying arrays!

In [43]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


b = a makes b point to the SAME array that a is, to prevent it, use .copy()

In [44]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]
