In [2]:
import numpy as np

## Mathematics

### The Basics

In [3]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a + 2

array([3, 4, 5, 6])

In [5]:
a - 2

array([-1,  0,  1,  2])

In [6]:
a * 2

array([2, 4, 6, 8])

In [7]:
a / 2 # converts to float 😧

array([0.5, 1. , 1.5, 2. ])

In [8]:
a ** 2

array([ 1,  4,  9, 16])

In [9]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [10]:
a * b

array([1, 0, 3, 0])

In [11]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [14]:
a = np.ones((2,3),dtype='int64')
print(a)
b = np.full((3,2),2)
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [15]:
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

Find more here: https://numpy.org/doc/stable/reference/routines.linalg.html

### Statistics

In [17]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.min(stats)

np.int64(1)

In [22]:
np.min(stats, axis=1)

array([1, 4])

In [19]:
np.max(stats)

np.int64(6)

In [23]:
np.sum(stats)

np.int64(21)